language: android

android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.1
    # The SDK version used to compile your project
    - android-23
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - chmod +x gradlew

script:
    - ./gradlew testDebugUnitTest
    - ./gradlew build

deploy:
    provider: releases
    api_key: ${GITHUB_TOKEN}
    file: "/home/travis/build/dcampogiani/LooxLikeClient/app/build/outputs/apk/app-debug.apk"
    skip_cleanup: true
    on:
        tags: true